Feature/style 1
francieleferraz/html-css pull request #3
Opened 2024-09-24 14:49 UTC by francieleferraz

Criei uma branch chamada feature/style-1 e adicionei algumas coisas no arquivo CSS.

https://dev.azure.com/giro-tech/GTSec/_sprints/taskboard/GTSec%20Team/GTSec/gtsec-1.0.62?System.AssignedTo=franciele.ferraz%40girotech.com.br&workitem=5009

2024-09-24 18:09 UTC, chrisAcarneiro commented
@francieleferraz Resolver conflitos com a develop

2024-09-24 18:40 UTC, francieleferraz commented
> @francieleferrazResolver conflitos com o desenvolvimento

@chrisAcarneiro eu acho que deu certo, pode confirmar por favor?

2024-09-24 19:09 UTC, chrisAcarneiro commented
@francieleferraz Deu certo :+1:

2024-09-25 12:16 UTC, artur-pinheiro-giro-tech requested changes

2024-09-25 12:16 UTC, artur-pinheiro-giro-tech commented on index.html
> +        UEPG e atualmente estou cursando <strong class="cursos-destaque">Análise e Desenvolvimento de Sistemas</strong> na PUCPR.</p>
a classe `cursos-destaque` não existe no seu arquivo CSS.

2024-09-25 12:42 UTC, francieleferraz commented on index.html
> +        UEPG e atualmente estou cursando <strong class="cursos-destaque">Análise e Desenvolvimento de Sistemas</strong> na PUCPR.</p>
Sempre que eu criar uma classe, ela obrigatoriamente tem que estar no arquivo CSS então?

2024-09-25 12:42 UTC, francieleferraz commented on index.html
> +        UEPG e atualmente estou cursando <strong class="cursos-destaque">Análise e Desenvolvimento de Sistemas</strong> na PUCPR.</p>
@artur-pinheiro-giro-tech

2024-09-25 12:48 UTC, artur-pinheiro-giro-tech commented on index.html
> +        UEPG e atualmente estou cursando <strong class="cursos-destaque">Análise e Desenvolvimento de Sistemas</strong> na PUCPR.</p>
na realidade o HTML não deve possuir classes que não existam no arquivo de CSS. Nesse caso, não faz diferença essa classe estar aplicada ali ou não, nada muda na apresentação da tela no navegador

2024-09-25 14:49 UTC, francieleferraz commented on index.html
> +        UEPG e atualmente estou cursando <strong class="cursos-destaque">Análise e Desenvolvimento de Sistemas</strong> na PUCPR.</p>
entendi, pode recusar essa PR então. Vou subir as últimas atualizações com esse ajuste nessa mesma branch, pode ser?

2024-09-26 14:22 UTC, chrisAcarneiro approved these changes

2024-09-26 14:57 UTC, artur-pinheiro-giro-tech commented on index.html
> +            Sistemas</strong> na PUCPR.</p>
cuidado com o uso do flex junto com outras tags dentro. Ao aplicar o flex com o column nesse parágrafo, é interpretado que deve-se colocar cada strong em uma linha.

2024-09-26 14:58 UTC, artur-pinheiro-giro-tech approved these changes

2024-09-26 15:03 UTC, merged